services:
  - type: web
    name: screenshot-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: screenshot-api
          property: port
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: screenshot-api-disk
      mountPath: /tmp
      sizeGB: 1